### ISSUE TITLE
Ability to conditionally add packages with environment variables

### ISSUE THREAD

**Issue by zippy1981** [kristophjunge/docker-test-saml-idp#1]
It would be nice to be able to add things like vim from docker-compose.yml without writing a separate docker file. I propose the environment variable `SIMPLESAMLPHP_DPKGS` that takes a comma separated list of packages e.g.

>SIMPLESAMLPHP_DPKGS="vim,git"

If that variable is set then docker should perform `apt-get update` and then `apt-get install [packages]`.

**Comment by kristophjunge** [comment]
Thank you very much for your Feedback.

I understand your need for Vim but i think its not the right approach do apply a generic solution with environment variables here.

Docker uses environment variables at runtime. They cannot be used at build time. To make it working with an environment variable i would have to add a small start script that performs the installation on container startup.

Another option is to use arguments in the Dockerfile with the ARG command. That would be used at build time. The user would not have to edit the Dockerfile. Instead he would have to rebuild the container while passing the custom argument. That would be the right way, but the user would still have to build and use a custom version of the container. So far i think the mostly Dockerway to the solution is extending the Dockerfile with FROM.

The goal of this container is to have it as most plug & play as possible. For now i have just added Vim to the installed packages. Since the container is for development and debugging purpose only its ok to have common debug tools preinstalled.

If you need anything else please let me know.
